name = "pixel"
main = "src/worker.js"
compatibility_date = "2025-08-16"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

[observability.logs]
enabled = true

[vars]
DOMAIN = ".test-123123123.store"

[[routes]]
pattern = "test-123123123.store/p1.js"
zone_name = "test-123123123.store"
