name = "pixel"
main = "src/worker.js"
compatibility_date = "2025-08-26"

[observability.logs]
enabled = true

[vars]
DOMAIN = ".test-123123123.store"
ENC_KEY = "11111111111111111111111111111111"
# ENC_KEY is secret: set via `wrangler secret put ENC_KEY`
